spring:
  profiles.active: "컨텐츠솔루션_샘플-본문"
---
spring:
  profiles: "컨텐츠솔루션_샘플-본문"

job:
  book-title: "컨텐츠솔루션_샘플-본문"
  languages: KR
  min-word-size: 1
  pdf-resource: "컨텐츠솔루션 국3-1 샘플-본문"
  pre-filter:
  pattern-filter:
  
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 10.0
  max-font-size: 20.0
  
  box-uprise: 0f
  cover-text: "yes"
  text-color: "2955"
  background-color: "2955"
  is-fill-background: "yes"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 16
  doc-root: "E:\\pdf_jobs\\changbee\\contents-solution\\"
  textListener: "PDFBOX"
---
spring:
  profiles: hackers_toeic_listening

job: 
  book-title: "해커스 토익 리스닝"
  languages: EN
  min-word-size: 2
  pdf-resource: hackers_toeic_listening
  pre-filter: 
  pattern-filter: "([Pp]{1}[1-4]{1}[_]{1}[\\x{3130}-\\x{318F}\\x{AC00}-\\x{D7AF}]{2,4}[_]{1}[0-9]{2}[\\.]{1}[a-zA-Z3]{3})"
  pattern-type: AUDIO
  patternURL: "http://107.191.60.255/resources/audio/hackers/Part1/"
  min-pattern-size: 2
  search-site: "//endic.naver.com/search.nhn?target=endic&query="
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  cover-text: "yes"
  text-color: "519"
  background-color: "white"
  is-fill-background: "no"
  min-font-size: 8.0
  max-font-size: 20.0
  box-uprise: 0
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 30
  doc-root: "\\pdf_jobs\\"
---
spring:
  profiles: cn_master1
  
job: 
  book-title: "중국어 마스터 다락원"
  languages: CN
  min-word-size: 1
  pdf-resource: cn_master1
  pre-filter: ""
  pattern-filter: 
  patternURL: "https://www.youtube.com/watch?v=aCs-ne2YTPE&list=PLSLe-MImsVV-ztbUA2Ij76t5o5PJkhj83&index=2"
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "cndic.naver.com/search.nhn?target=cndic&query="
  cover-text: "yes"
  text-color: "1817"
  background-color: "white"
  is-fill-background: "no"
  min-font-size: 8.0
  max-font-size: 20.0
  box-uprise: 0
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"  
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 30
  doc-root: "\\pdf_jobs\\"
---
spring:
  profiles: cretec-opti-555

job:
  book-title: "크레텍 책임 555"
  languages: ""
  min-word-size: 2
  pdf-resource: cretec-opti-555
  pre-filter: "[0-9\\- ]+"
  pattern-filter: "([1-9]{1}[0-9]{2}-[0-9]{4}|[\\s]{1,3}-{1}[0-9]{4})"
  patternSelector: "([0-9]{0,3})-([0-9]{4})"
  pattern-type: ORDER
  min-pattern-size: 5
  patternURL: "http://test.cretec.kr/nctx/order/search.do?prod_cd="
  search-site: ""
  min-font-size: 6.0
  max-font-size: 20.0
  box-uprise: 1.0
  boxWidthGrow: 5.0
  boxHeightGrow: 1.0
  cover-text: "yes"
  text-color: "525"
  background-color: "white"
  is-fill-background: "yes"
  stamp-message: "이 문서는 펜을 테스트하기 위한 샘플입니다(비매품)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  target-printer: COLOR_LASER
  made-by: IRON
  start-page: 2
  end-page: 30
  doc-root: "\\pdf_jobs\\크레텍\\"
---
spring:
  profiles: "cretec 가격표테스트"

job:
  book-title: "cretec가격표테스트"
  languages: ""
  min-word-size: 2
  pdf-resource: cretec가격표테스트
  pre-filter: "[0-9\\- ]+"
  pattern-filter: "([1-9]{1}[0-9]{2}-[0-9]{4}|[\\s]{1,3}-{1}[0-9]{4})"
  patternSelector: "([0-9]{0,3})-([0-9]{4})"
  pattern-type: ORDER
  min-pattern-size: 4
  patternURL: "http://test.cretec.kr/nctx/order/search.do?prod_cd="
  search-site: ""
  min-font-size: 7.0
  max-font-size: 12.0
  box-uprise: 0.0
  boxWidthGrow: 5.0
  boxHeightGrow: 1.0
  cover-text: "yes"
  text-color: "2955"
  background-color: "white"
  is-fill-background: "yes"
  stamp-message: "이 문서는 펜을 테스트하기 위한 샘플입니다(비매품)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  target-printer: COLOR_LASER
  made-by: IRON
  start-page: 1
  end-page: 8
  doc-root: "\\pdf_jobs\\크레텍\\"
---
spring:
  profiles: "cretec카탈로그테스트"

job:
  book-title: "cretec 카탈로그 테스트"
  languages: ""
  min-word-size: 2
  pdf-resource: "cretec카탈로그테스트"
  pre-filter: "[0-9\\- ]+"
  pattern-filter: "([1-9]{1}[0-9]{2}-[0-9]{4}|[\\s]{1,3}-{1}[0-9]{4})"
  patternSelector: "([0-9]{0,3})-([0-9]{4})"
  pattern-type: ORDER
  min-pattern-size: 4
  patternURL: "http://test.cretec.kr/nctx/order/search.do?prod_cd="
  search-site: ""
  min-font-size: 6.0
  max-font-size: 20.0
  box-uprise: 1.0
  boxWidthGrow: 5.0
  boxHeightGrow: 0.0
  cover-text: "yes"
  text-color: "2955"
  background-color: "white"
  is-fill-background: "yes"
  stamp-message: "이 문서는 펜을 테스트하기 위한 샘플입니다(비매품)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\fine\\책임기업-opti-555_페이지_%02d_pbh.tif"
  target-printer: COLOR_LASER
  made-by: IRON
  start-page: 1
  end-page: 8
  doc-root: "\\pdf_jobs\\크레텍\\"
---
spring:
  profiles: japanese_grammar_guide

job:
  book-title: "일본어 문법"
  languages: JP,EN
  min-word-size: 1
  pdf-resource: japanese_grammar_guide
  pre-filter: ""
  pattern-filter: 
  min-pattern-size: 2 
  max-font-size: 20.0
  pattern-type: AUDIO
  search-site: "http://jpdic.naver.com/search.nhn?target=jpdic&query="
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "no"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  min-font-size: 6.0
  text-color: "804"
  background-color: "white"
  is-fill-background: "yes"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 3
  end-page: 3
  doc-root: "\\pdf_jobs\\"
---
spring:
  profiles: EBS-2015-korean-Atype-main

job:
  book-title: "EBS 수능특강 국어A형"
  languages: KR
  min-word-size: 2
  pdf-resource: "EBS-2015-korean-Atype-main"
  pre-filter: "[\\x{3130}-\\x{318F}\\x{AC00}-\\x{D7AF}A-Za-z0-9_\\'\\’\\.\\,\\?\\(\\)'\\-\\s\\t\\n\\r ]+"
  pattern-filter: 
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 6.0
  max-font-size: 20.0
  text-color: "804"
  is-fill-background: "yes"
  background-color: "white"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "no"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 26
  doc-root: "\\pdf_jobs\\"
---
spring:
  profiles: success_principle

job:
  book-title: "석세스프린서플-본문"
  languages: KR
  min-word-size: 2
  pdf-resource: "석세스프린서플-본문"
  pre-filter: ""
  pattern-filter: 
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 8.0
  max-font-size: 20.0
  cover-text: "no"
  text-color: "804"
  is-fill-background: "yes"
  background-color: "white"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 16
  doc-root: "\\pdf_jobs\\changbee\\성공의원리\\"
  textListener: "PDFBOX"
---
spring:
  profiles: "근현대사본문최종2도"

job:
  book-title: "근현대사본문최종2도"
  languages: KR
  min-word-size: 1
  pdf-resource: "근현대사본문최종2도"
  pre-filter: ""
  pattern-filter: ""
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 9.5
  box-uprise: 0
  cover-text: "yes"  
  text-color: "804"
  is-fill-background: "no"
  background-color: "white"
  
  embedding-coord-image: "yes"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 30
  doc-root: "\\pdf_jobs\\changbee\\성공의원리\\"
---
spring:
  profiles: Emerson-Life

job:
  book-title: "에머슨 인생학"
  languages: KR
  min-word-size: 1
  pdf-resource: "에머슨 인생학-본문(최종)"
  pre-filter: ""
  pattern-filter: ""
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 8.5
  box-uprise: 0.0
  cover-text: "no"
  text-color: "804"
  background-color: "white"
  is-fill-background: "yes"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 24
  doc-root: "\\pdf_jobs\\changbee\\성공의원리\\"
---
spring:
  profiles: "9-1-3국"

job:
  book-title: "9-1-3국"
  languages: KR,EN
  min-word-size: 1
  pdf-resource: "9-1-3국"
  pre-filter: ""
  pattern-filter: ""
  pattern-type: AUDIO
  min-pattern-size: 2
  search-site: "krdic.naver.com/search.nhn?target=krdic&query="
  min-font-size: 8.5
  box-uprise: -10.0
  cover-text: "no"
  text-color: "804"
  background-color: "white"
  is-fill-background: "yes"
  stamp-message: "This document is only for pen testing(SAMPLE ONLY)"
  include-coord-image: "yes"
  coord-image-clipping: "yes"
  coord-image-resource: "\\pdf_jobs\\page_images\\다락원_중국어_마스터_Step_1_images\\다락원 중국어 마스터 Step 1_페이지_%03d_vry.tif"
  target-printer: LASER_PRINTER
  made-by: IRON
  start-page: 1
  end-page: 30
  doc-root: "\\pdf_jobs\\changbee\\창비교육-컨텐츠솔루션\\"
---
dicttype:
  dictionary: 
  - KR,http://krdic.naver.com/search.nhn?sLn=kr&query=
  - EN,http://endic.naver.com/search.nhn?sLn=en&query=
  - CN,http://cndic.naver.com/search/all?q=
  - JP,http://jpdic.naver.com/search.nhn?dic_where=jpdic&query=
  - HAN,http://hanja.naver.com/search?query=
---
userdict: 
  words: 
    - 표준어,http://krdic.naver.com/detail.nhn?docid=40789600
    - 사투리,http://krdic.naver.com/detail.nhn?docid=19500900
    - 방언,http://krdic.naver.com/detail.nhn?docid=15828500
    - 소금물,http://krdic.naver.com/detail.nhn?docid=21746100
    - 딤채,http://krdic.naver.com/detail.nhn?docid=11085200
    - 투가리,http://krdic.naver.com/detail.nhn?docid=39760700
    - 규칙성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,규칙성
    - 의사소통,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,의사소통
    - 사회성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,사회성
    - 역사성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,역사성
    - 세계화,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,세계화
    - 국제화,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,국제화
    - 필연적,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,필연적
    - 기호성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,기호성
    - 자의성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,자의성
    - 보편성,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,보편성
    - 비판적,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,비판적
    - 창의적,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,창의적
    - 반성적,http://krdic.naver.com/search.nhn?dic_where=krdic&query=,반성적
  medias: 
    - ① 학습 내용 정리,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,107쪽 1번 소단원 (1) 학습 내용 정리.ppt
    - ② \[인터뷰 \]  언어의 종류,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,107쪽 2번 한성우 이 세상에는 얼마나 많은 언어가 있나요.wmv
    - ③ \[인터뷰 \]  언어의 특성들 간의 관계,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/107,"107쪽 3번 한성우 언어의 특성들은 서로 어떤 관련이 있나요.wmv
    - ④ 언어의 특성,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,107쪽 4번 언어의 특성.ppt
    - ①‘기호’란,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,108쪽 1번 기호란.ppt
    - ① 토마토와,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,114쪽 1번 토마토와 방울토마토.jpg
    - ① 구름다리 사진,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,115쪽 1번 구름다리 사진.jpg
    - ② 부채 도끼 사진,,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,115쪽 2번 부채 도끼 사진.jpg
    - ① 표준어와,http://107.191.60.255/resources/changbee/smart-teacher/3-1-korean/section-3/,116쪽 1번 표준어와 방언의 세력 다툼.ppt
---